PRIN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('one/',include('one.urls')),
    path('admin/', admin.site.urls),
]

one/urls.py
from logging import PercentStyle
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
app_name = 'one'
urlpatterns = [
    path('', views.index, name='index'), ## home page application one
    path('get_sll/', views.get_sll, name='read'), ## List the SLL on neo4j
    path('sll/',views.sll, name='populate'), ## polpola tutto il neo4j
    path('delete/',views.del_all, name='delete'), ## svuota il neo4j
    path('grafo/<int:fil>/',views.get_grafo, name='grafo'), ## visualizza il grafo 3d e la mappa
    path('map/<int:fil>/', views.get_map, name='map'), ## visualizza solo la mappa
]

one/models.py
from django.db import models

from typing import List
from neomodel import (config, StructuredNode, StringProperty, IntegerProperty,
    UniqueIdProperty, RelationshipTo, StructuredRel, DateTimeProperty)
from neomodel.contrib.spatial_properties import NeomodelPoint
from neomodel.properties import FloatProperty

config.DATABASE_URL = 'bolt://neo4j:stupidoFlanders@localhost:7687'
# Create your models here.
class SllRel(StructuredRel):
    imprese = IntegerProperty()
    
class Ateco(StructuredNode):
    code = IntegerProperty(unique_index=True, required=True)
    description = StringProperty()
    url = StringProperty()

class Sll(StructuredNode):
    code = IntegerProperty(unique_index=True, required=True)
    name = StringProperty()
    sll_ateco = RelationshipTo(Ateco, 'contiene', model=SllRel)
    #location = NeomodelPoint((0,0),crs='wgs-84')
    lat = FloatProperty()
    lng = FloatProperty()

one/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, response
from django.urls.conf import include
from django.template.response import  TemplateResponse
from numpy.core.numeric import NaN
from .models import Ateco, Sll, SllRel
from .modulo1 import MyImport as Mi
from neomodel import db
from neomodel.contrib.spatial_properties import NeomodelPoint
import json

# Create your views here.
template_home = 'one/home.html'
template_uno = 'one/uno.html'
template_due = 'one/due.html'
data_path = '/home/azureuser/PRIN/static/data/'

def sll(request):
    ateco2021 = Mi.importaAteco(data_path+'Ateco2007.csv') #import description of ATECO codes
    query = 'MATCH (n) DETACH DELETE n'
    db.cypher_query(query)

    df = Mi.importa_csv(data_path+'food.csv') #import the sll and Ateco nodes 
    d= df.set_index('code')
    punto = Mi.importa_sll_coordinates(data_path+'qgis3.geojson') #iimport the centroid coordinates of Sll 
    for j in d.columns: 
        if (j !=  'name'):
            i = "{}.{}".format(str(j)[0:2],str(j)[2:4])
            des = ateco2021.loc[i]['descrizione']
            Ateco(code=j, description=des).save() # Create the Ateco nodes
    for i in d.index:   
        try:
            sll = Sll(code=i, name = d.loc[i][0], lat=punto[i][1], lng=punto[i][0]).save() # Create the Sll nodes
        except:
            pass
        n=0
        for j in d.loc[i]: ## per ogni Sll aggiunge le relazioni con gli Ateco
            if n > 0:
                a = Ateco.nodes.get(code=int(d.columns[n]))
                sll.sll_ateco.connect(a,{'imprese':j})
            n=n+1
    ## Mostra i risultati
    return get_sll(request)
 
def index(request):
    return TemplateResponse(request, template_home, {'titolo': "Iniziamo"})

def get_sll(request):
    sll_list=Sll.nodes.all()
    ateco_list=Ateco.nodes.all()
    return TemplateResponse(request, template_home, {'sll_list':sll_list, 'ateco_list':ateco_list, 'msg': "Database Popolato"})

def del_all(request):
    query = 'MATCH (n) DETACH DELETE n'
    db.cypher_query(query)
    return TemplateResponse(request, template_home, {'msg': "Database Pulito"})

def get_map(request, fil=0):
    query = 'MATCH (n)-[r:contiene]->(m) WHERE r.imprese>' + str(fil) + ' RETURN { id: n.code, label:head(labels(n)), caption:n.name, lat:n.lat, lng: n.lng } as source, { id: id(m), label:head(labels(m)), caption:m.code } as target, { weight:log(r.imprese)/2, type:type(r), imprese: r.imprese} as rel' 
    results, meta = db.cypher_query(query)
    shapes={}
    with open(data_path+'SLL.json','r') as f:
        shapes = json.load(f)
    return TemplateResponse(request, template_due,{'nodi': results, 'filtro':fil, 'shapes':shapes}) 

def get_grafo(request, fil=0):
    query = 'MATCH (n)-[r:contiene]->(m) WHERE r.imprese>' + str(fil) + ' RETURN { id: n.code, label:head(labels(n)), caption:n.name, lat:n.lat, lng: n.lng } as source, { id: m.code, label:head(labels(m)), caption:m.code, description:m.description} as target, { weight:log(r.imprese)/2, type:type(r), imprese: r.imprese} as rel' 
    results, meta = db.cypher_query(query)
    shapes={}
    with open(data_path+'SLL.json','r') as f:
        shapes = json.load(f)
    return TemplateResponse(request, template_uno,{'nodi': results, 'filtro':fil, 'shapes':shapes}) 

one/templates/one/due.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>
    
    <title>PRIN 2020 Test</title>

  <style>
    #mapid{
      height: 800px;
    };

  </style>
</head>
<body { margin: 0; }>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/one/">PRIN</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Operazioni su DB
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'one:delete' %}">Pulisci Database</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" onclick="popolaDb()">Popola il Database</a></li>
                </ul>
              </li>
            </ul>
            <span class="nav-item" style='color:green'> Collegamenti con minimo </span>
            <form class="d-flex">
              <input class="form-control me-2" type="text" placeholder="aziende" aria-label="Filtra">
              <button class="btn btn-outline-success" type="submit">Filtra</button> 
            </form>
          </div>
        </div>
      </nav>
<main>
    <div class="container-fluid " style="position:relative; padding-top: 60px;">
        <h1 id="titolo">{{titolo}}</h1>
        <div class=" container-fluid">

        <!-- <input type="checkbox" class="btn-check " id="btn-map" autocomplete="off" onclick="Toggle_Map()">
        <label id="btn-toggle-mappa" class="btn btn-primary" for="btn-map">Mappa ON</label> -->

        <hr>
        <div  class="d-flex justify-content-center">
            <div id="spinner" class="spinner-border text-success" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
        </div>

        <div id="mapid"></div>
      </div>
    </div>
  </main>

  <script>
  

 </script>
    <script>

      var mymap = L.map('mapid', {
        zoomAnimation: true,
      }).setView([39.309993, 16.250193], 8);
      $("#spinner").hide()
     
    $( "form" ).submit(function( event ) {
     $("#spinner").show();
     fil = parseInt($( "input" ).first().val());
     if (isNaN(fil)) {
        alert("deve Essere un Intero maggiore uguale a zero")
     } else
      {
        // $( "span" ).text( fil ).show().fadeOut( 1000 );
        window.location.href= "/one/map/"+ fil + "/"
     } 
     event.preventDefault();
});
  </script>

<script>

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 20,
    id: 'mapbox/streets-v11',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'pk.eyJ1IjoicGllYmF0IiwiYSI6ImNrbTlkNGQxeDE0bjEydm16bGw4bzF5NG0ifQ.oytwdA8i5yX6ErDHRRj-zw'
  }).addTo(mymap);
  
  var geojsonFeature = {{ shapes|safe }};
  var nodes = {{nodi|safe}};
    
  var gl = L.geoJSON(geojsonFeature, {
    color: '#ff0000',
    opacity: 1,
    fillColor:'#0000f0',
    fillOpacity:0.4,
    weight: 1,
    filter: function(feature, layer) {
        return (true) ;
    },
    //onEachFeature: onEachFeature
})//.addTo(mymap);
for ([o,i] of Object.entries(gl._layers)) {
  for ([j, element] of Object.entries(nodes)){
    if ( element[0].id == i.feature.properties.SLL_2011) {
    i.addTo(mymap)
    }
  }

}

var nodes = {{nodi|safe}};
var lc= Object;

  for (const [k , element] of Object.entries(nodes)) {
    // element[0] = source
    // element[1] = target
    // element[2] = link
  try {
      ll=L.latLng(element[0].lat,element[0].lng)
      //console.log(ll)
      lc[element.id] = L.circle(ll, {
          color: '#0000ff',
          fillColor: '#0000ff',
          fillOpacity: 0.5,
          radius: 2000
      }).addTo(mymap);
      lc[element.id].on('click', onMarkerClick)
      
    // L.marker(ll)
    // .on('click', onMarkerClick)
    // .addTo(mymap);
     
    } catch
    {
      console.log(ll);
    }
  };

   function onMarkerClick(e){
   
   
   }; 

  </script>

 
</body>
</html>

one/templates/one/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
 
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/one/">PRIN</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Operazioni su DB
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'one:delete' %}">Pulisci Database</a></li>
                  <!-- <li><a class="dropdown-item" href="/one/delete/">Pulisci Database</a></li> -->
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" onclick="popolaDb()">Popola il Database</a></li>
                </ul>
              </li>
            </ul>
            <span class="nav-item" style='color:green'> Collegamenti con minimo </span>
            <form class="d-flex">
              <input class="form-control me-2" type="text" placeholder="aziende" aria-label="Filtra">
              <button class="btn btn-outline-success" type="submit">Filtra</button> 
            </form>
          </div>
        </div>
      </nav>

    {% block  content%}
    {% if msg %}
    <div class="container-fluid">
     <div class="alert alert-success" role="alert">
      {{msg}}
    </div>
    </div>
    {% endif %}

    <div class="container">
      <div calss="row-cols-2">
        <div class="col-xl-6">
            {% if sll_list %}
            <h2>SLL List</h2>
            <ul>
                {% for sll in sll_list %}
                <li>
                    {{ sll.code }} {{sll.name}} {{sll.lat}} {{sll.lng}}
                </li>
                {% endfor %}
            </ul>
            {% endif %} 
        </div>
        <div class="col-xl-6">
            {% if ateco_list %}
            <h2>Ateco List</h2>
            <ul>
                {% for ateco in ateco_list %}
                <li>
                    {{ ateco.code }} {{ateco.description}}
                </li>
                {% endfor %}
            </ul>
            {% endif %} 
        </div>
      </div>
    </div>
    {% endblock  %}

<script>

   function popolaDb() {
        $("#spinner").show();
        window.location.href='/one/sll/'
    }
    var fil = 0
    $( "form" ).submit(function( event ) {
        $("#spinner").show();
        fil = parseInt($( "input" ).first().val());
        if (isNaN(fil)) {
            alert("deve Essere un Intero maggiore uguale a zero")
        } else
          {
            // $( "span" ).text( fil ).show().fadeOut( 1000 );
            window.location.href= `/one/grafo/${fil}`
        } 
        event.preventDefault();
      });

</script>
</body>
</html>

one/templates/one/test.html
<head>
    <style> body { margin: 0; } </style>
  
    <script src="//unpkg.com/three"></script>
    <script src="//unpkg.com/3d-force-graph"></script>
    <script src="//unpkg.com/three-spritetext"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
   <script src="https://unpkg.com/shpjs@latest/dist/shp.js"></script>
  <style>
    #mapid {
      height: 500px;
    }
  </style>

  </head>
  
  <body>
    <div id="mapid"></div>
    <div class="container">
      <div id="3d-graph"></div>
    </div>
    
  
    <script>
       var mymap = L.map('mapid').setView([39.309993, 16.250193], 13);
      // Random tree
      const N = 30;
      var sll = [{id:1, lat:39.309993, lng: 16.250193, label: 'a'}, {id:2, lat:38.95933332688675, lng: 16.28756668990772, label: 'b'}];
      const gData = {
        nodes: sll,
        links: [{source:1, target:2, weight:3, imprese:30}]
      };


      console.log(sll);
      const graph = ForceGraph3D()
        (document.getElementById('3d-graph'))
          .linkWidth('weight')
          .nodeAutoColorBy('label')
          .linkThreeObjectExtend(true)
          .linkThreeObject(link => {
            // extend link with text sprite
            const sprite = new SpriteText(`${link.imprese}`);
            sprite.color = 'lightgrey';
            sprite.textHeight = 1.5;
            return sprite;
          })
          .onNodeClick(node => {
            // Aim at node from outside it
            const distance = 100;
            const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
            graph.cameraPosition(
              { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
              node, // lookAt ({ x, y, z })
              3000  // ms transition duration
              );
              mymap.panTo(L.latLng(node));
          })
          .graphData(gData);


      
    </script>

    <script>
    
   
    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1,
      accessToken: 'pk.eyJ1IjoicGllYmF0IiwiYSI6ImNrbTlkNGQxeDE0bjEydm16bGw4bzF5NG0ifQ.oytwdA8i5yX6ErDHRRj-zw'
    }).addTo(mymap);
    sll.forEach(element => {
      L.marker([element.lat,element.lng])
      .on('click', onMarkerClick)
      .addTo(mymap);
    });

    {% comment %} 
    var geojsonFeature = Object.assign({},{{geoj|safe}})
    L.geoJSON(geojsonFeature).addTo(mymap);

    var shapeFeature = Object.assign({},{{shp|safe}})
    L.shapefile(shapeFeature).addTo(mymap);  
 {% endcomment %}

    function onMarkerClick(e){
      var node={};
      gData.nodes.forEach(ele => {
        if ( L.latLng(ele).equals(e.latlng)) {
          node = ele;
        }
      });
      const distance = 100;
      const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
      graph.cameraPosition(
        { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
        node, // lookAt ({ x, y, z })
        3000  // ms transition duration
        );
    };
    </script>
  </body>

one/templates/one/uno copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="//unpkg.com/3d-force-graph"></script>
    <script src="//unpkg.com/three"></script>
    <script src="//unpkg.com/three-spritetext"></script>
    <script src="https://unpkg.com/neo4j-driver"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    
  
    <title>PRIN 2020 Test</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">PRIN</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Operazioni su DB
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'one:delete' %}">Pulisci Database</a></li>
                  <!-- <li><a class="dropdown-item" href="/one/delete/">Pulisci Database</a></li> -->
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" onclick="popolaDb()">Popola il Database</a></li>
                </ul>
              </li>
            </ul>
            <span class="nav-item" style='color:green'> Collegamenti con minimo </span>
            <form class="d-flex">
              <input class="form-control me-2" type="text" placeholder="aziende" aria-label="Filtra">
              <button class="btn btn-outline-success" type="submit">Filtra</button> 
            </form>
          </div>
        </div>
      </nav>


    <div class="container-fluid">
        <h1 id="titolo">{{titolo}}</h1>
        <input type="checkbox" class="btn-check" id="btn-check" autocomplete="off" onclick="Toggle_Testo()">
        <label id="btn-check-label" class="btn btn-primary" for="btn-check">Testo</label>
        <hr>
        <div  class="d-flex justify-content-center">
            <div id="spinner" class="spinner-border text-success" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
        </div>

        {% block content %}
        {% if filtro >= 0 %}
        <h5>Filtrata per <span id='filtro'>{{filtro}}</span></h5>
        {% endif %}
        {% if sll_list %}
        <h2>SLL List</h2>
        <ul>
            {% for sll in sll_list %}
            <li>
                {{ sll.code }} {{sll.name}}
            </li>
            {% endfor %}
        </ul>
        {% endif %} 
        {% endblock %}
        <div class="card">
          <div class="card-body">
            <div id="details" class="card-text"></div>
          </div>
        </div>
        <div class="container-fluid" style="padding-right: 10px;">
          <div id="3d-graph"  style=" background-color: black;"></div>
        </div>
    </div>
    <script>

      var testo = false;
      Grafo();

      function Toggle_Testo() {
        testo = ! testo;
        if (testo) {
          $('#btn-check-label').text("Sfere");
        }else {
          $('#btn-check-label').text("Testo");
        }
        Grafo();
      }
      function Grafo() {
        $("#spinner").hide()
      const elem = document.getElementById('3d-graph');
      var fil = 10 //document.getElementById('filtro').innerText;
      const driver = neo4j.driver("bolt://10.10.1.213", neo4j.auth.basic("neo4j", "stupidoFlanders"),{encrypted: false});
      const session = driver.session({database:"neo4j"});
      const start = new Date()
      session
      .run('MATCH (n)-[r:contiene]->(m) WHERE r.imprese >= '+fil+' RETURN { id: id(n), label:head(labels(n)), caption:n.name } as source, { id: id(m), label:head(labels(m)), caption:m.code } as target, { weight:log(r.imprese)/2, type:type(r), imprese: r.imprese} as rel LIMIT $limit', {limit: neo4j.int(5000)})
      .then(function (result) {
        const nodes = {}
        const links = result.records.map(r => { 
	       var source = r.get('source');source.id = source.id.toNumber();
           nodes[source.id] = source;
	       var target = r.get('target');target.id = target.id.toNumber();
           nodes[target.id] = target;
           var rel = r.get('rel');
	       return Object.assign({source:source.id,target:target.id}, rel);
	    });
        session.close();

        
        // console.log(links.length+" links loaded in "+(new Date()-start)+" ms.")
        const gData = { nodes: Object.values(nodes), links: links}
        // console.log(gData);
        const Graph = ForceGraph3D()(elem)
                      .graphData(gData)
                      .nodeAutoColorBy('label')
                      .nodeVal('size')
                      .linkAutoColorBy('type')
                      .linkWidth('weight')
                      .nodeLabel(node => `${node.label}: ${node.caption}`)
                      .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
                      .onNodeDragEnd(node => {
                        node.fx = node.x;
                        node.fy = node.y;
                        node.fz = node.z;
                      })
                      .linkThreeObjectExtend(true)
                      .onNodeClick(node => {
                        $('#details').text(node.label + ' ' + node.caption);
                        // Aim at node from outside it
                        const distance = 40;
                        const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
                        Graph.cameraPosition(
                          { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio }, // new position
                          node, // lookAt ({ x, y, z })
                          3000  // ms transition duration
                          );
                      });
                      if (testo) {
                      Graph.linkThreeObject(link => {
                        // extend link with text sprite
                        const sprite = new SpriteText(`${link.imprese}`);
                        sprite.color = 'lightgrey';
                        sprite.textHeight = 1.5;
                        return sprite;
                      })
                      .linkPositionUpdate((sprite, { start, end }) => {
                          const middlePos = Object.assign(...['x', 'y', 'z'].map(c => ({
                          [c]: start[c] + (end[c] - start[c]) / 2 // calc middle point
                        })))
                        Object.assign(sprite.position, middlePos)
                      });
                    };
                      if (testo) {
                        Graph.nodeThreeObject(node => {
                        const sprite = new SpriteText(node.caption);
                        sprite.material.depthWrite = false; // make sprite background transparent
                        sprite.color = node.color;
                        sprite.textHeight = 8;
                        return sprite;
                      });
                    };

                      Graph.d3Force('charge').strength(-120);

      })
      .catch(function (error) {
        console.log(error);
      });

      }
  </script>
  <script>
    function popolaDb() {
        $("#spinner").show();
        window.location.href="{% url 'one:populate' %}";
    }
    $( "form" ).submit(function( event ) {
     $("#spinner").show();
     fil = parseInt($( "input" ).first().val());
     if (isNaN(fil)) {
        alert("deve Essere un Intero maggiore uguale a zero")
     } else
      {
        // $( "span" ).text( fil ).show().fadeOut( 1000 );
        window.location.href="/one/read_node/"+fil+"/"
     } 
     event.preventDefault();
});
  </script>
</body>
</html>